language: node_js

node_js:
  - 10

sudo: false

cache:
  yarn: true
  directories:
    - app/node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

install:
  - yarn --cwd ./app install

jobs:
  include:
    - stage: test
      script:
        - cd ./app
        - yarn lint
        - yarn typecheck
        - yarn test

notifications:
  email: false
