version: '3'

services:
  app:
    build: ./app
    container_name: portalgist
    tty: true
    ports:
      - 3000:3000
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
      - yarn-cache:/usr/local/share/.cache/yarn

volumes:
  yarn-cache: